### ISSUE TITLE
how to change annotation's color ???????

### ISSUE THREAD

**Issue by yeahliv** [uloco/syntax-highlighting-samples#1]
I'm going mad, plz

**Comment by uloco** [comment]
What are you talking about? In what theme/editor ...
This is just an example repo to test different languages in your preferred editor.

**Comment by yeahliv** [comment]
Em...... Sorry , I'm using Bluloco Light Theme , I've done it , haha , I didn't look at the link carefully , I thought this was Bluloco Light Theme

**Comment by uloco** [comment]
What is your problem with the annotation color?
Why and how did you change it?
