### ISSUE TITLE
How to customize some of the colors?

### ISSUE THREAD

**Issue by ghost** [uloco/syntax-highlighting-samples#2]
Hi,
Thanks for providing a nice color theme, but I want to change some of the color from what you provided. How can I do that? Thank you.

**Comment by uloco** [comment]
This is not a color theme repo, it's just a collection of code snippets to check them. Which theme are you talking about?

**Comment by ghost** [comment]
Sorry for not noticing it. I just opened the issue at this repo https://github.com/uloco/theme-bluloco-light
