### ISSUE TITLE
How switch between themes in VSC

### ISSUE THREAD

**Issue by eliassal** [uloco/syntax-highlighting-samples#3]
Hi, I installed your interesting theme in extensions in VSC but cant find how to switch to the new theme. I type ctrl+shift+P typye bluloco but it does not find anything.
Thanks for your help

**Comment by uloco** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/8818340/165070949-4de59ba9-0835-4bcc-8b8d-434846ee0ffa.png">

**Comment by eliassal** [comment]
Ok thanks, I do this but what should I chose?

**Comment by uloco** [comment]
Bluloco? 😄

**Comment by uloco** [comment]
I don't understand the problem...

**Comment by eliassal** [comment]
Thanks but it is not working, when I chose Bluloco always getting

![colorTheme](https://user-images.githubusercontent.com/8447864/165072665-c58af8cc-3c3b-443f-98fc-3a1e72695269.jpg)

**Comment by uloco** [comment]
you have errors in your settings file for some reason. Open it with command palette like so
<img width="628" alt="image" src="https://user-images.githubusercontent.com/8818340/165075773-0a3ecc07-0591-4d33-8490-59d22a4e76e4.png">

And afterwards look for red error marks. Clean up and save the file and after this you can change your theme

**Comment by eliassal** [comment]
So many thanks, correct, there was a missing colon in the settings file. Thanks to make this nice extensible for the community.
